In [1]:
import torch

In [ ]:
a = torch.tensor([2.,3.],requires_grad=True)

In [ ]:
b = a + 3
c = b * 3
out = c.mean()
out.backward()

In [ ]:
print(a.data)

In [ ]:
print(out.data.item())

In [ ]:
print(a.grad)

In [ ]:
print(b.grad)

In [ ]:
print(c.grad)

In [23]:
a = torch.tensor([[2.,4.]],requires_grad=True)
a

tensor([[2., 4.]], requires_grad=True)

In [24]:
b = torch.zeros(1,2)
b

tensor([[0., 0.]])

In [25]:
b[0,0] = a[0,0]**2 #+ a[0,1]
b[0,1] = a[0,1]**3 #+ a[0,0]
b

tensor([[ 4., 64.]], grad_fn=<CopySlices>)

In [26]:
out = 2 * b

In [27]:
out.backward(torch.Tensor([[1,1]]),retain_graph=True)

In [28]:
out.data

tensor([[  8., 128.]])

In [29]:
a.grad

tensor([[ 8., 96.]])